version: '3.1'

services:

  order-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: order-service
    ports:
      - "5433:5432"

  product-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: product-service
    ports:
      - "5434:5432"