version: '3.5'

networks:
  default:
    name: order-manager-net

services:

  consul:
    image: docker.io/hashicorp/consul
    container_name: consul
    networks:
      - default

  order-service:
    container_name: order-service
    build: ./order-service
    image: aswproject/order-service:2024-01
    environment:
      - SPRING_PROFILES_ACTIVE=order-service
      - ASW_ORDERMANAGER_ORDERSERVICE_INSTANCENAME=os1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-service-db:5432/orderservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - "consul"
      - "order-service-db"
    networks:
      - default

  order-service-db:
    container_name: order-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: orderservice
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data #TODO
      - "./postgres/order-service:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432" #TODO
    depends_on:
      - "consul"
    networks:
      - default

  product-service:
    container_name: product-service
    build: ./product-service
    image: aswproject/product-service:2024-01
    environment:
      - SPRING_PROFILES_ACTIVE=product-service
      - ASW_ORDERMANAGER_PRODUCTSERVICE_INSTANCENAME=os1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-service-db:5432/productservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - "consul"
      - "product-service-db"
    networks:
      - default

  product-service-db:
    container_name: product-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: productservice
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata1:/var/lib/postgresql/data #TODO
      - "./postgres/product-service:/docker-entrypoint-initdb.d"
    ports:
      - "5434:5432" #TODO
    depends_on:
      - "consul"
    networks:
      - default

  order-validation-service:
    container_name: order-validation-service
    build: ./order-validation-service
    image: aswproject/order-validation-service:2024-01
    environment:
      - SPRING_PROFILES_ACTIVE=order-validation-service
      - ASW_ORDERMANAGER_ORDERVALIDATIONSERVICE_INSTANCENAME=ov1
    depends_on:
      - "consul"
    networks:
      - default

  apigateway:
    container_name: apigateway
    build: ./api-gateway
    image: aswproject/apigateway:2024-01
    ports:
      - "8080:8080"
    depends_on:
      - "consul"
    networks:
      - default

volumes:
  pgdata: #TODO
  pgdata1: #TODO