version: '3.5'

networks:
  order-manager:
    name: order-manager-net

services:

  consul:
    image: docker.io/hashicorp/consul
    container_name: consul
    networks:
      - order-manager

  order-service:
    container_name: order-service
    build: ./order-service
    image: aswproject/order-service:2024-01
    environment:
      - SPRING_PROFILES_ACTIVE=order-service
      - ASW_ORDERMANAGER_ORDERSERVICE_INSTANCENAME=os1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-service-db:5432/orderservice
    depends_on:
      - "consul"
      - "order-service-db"
    networks:
      - order-manager

  order-service-db:
    container_name: order-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - order-service-db-data:/var/lib/postgresql/data
      - "./postgres/order-service:/docker-entrypoint-initdb.d"
    ports:
      - "5433:5432"
    depends_on:
      - "consul"
    networks:
      - order-manager

  product-service:
    container_name: product-service
    build: ./product-service
    image: aswproject/product-service:2024-01
    environment:
      - SPRING_PROFILES_ACTIVE=product-service
      - ASW_ORDERMANAGER_PRODUCTSERVICE_INSTANCENAME=os1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-service-db:5432/productservice
    depends_on:
      - "consul"
      - "product-service-db"
    networks:
      - order-manager

  product-service-db:
    container_name: product-service-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - product-service-db-data:/var/lib/postgresql/data
      - "./postgres/product-service:/docker-entrypoint-initdb.d"
    ports:
      - "5434:5432"
    depends_on:
      - "consul"
    networks:
      - order-manager

  order-validation-service:
    container_name: order-validation-service
    build: ./order-validation-service
    image: aswproject/order-validation-service:2024-01
    environment:
      - SPRING_PROFILES_ACTIVE=order-validation-service
      - ASW_ORDERMANAGER_ORDERVALIDATIONSERVICE_INSTANCENAME=ov1
    depends_on:
      - "consul"
    networks:
      - order-manager

  order-validation-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./postgres/order-validation-service/data:/var/lib/postgresql/data"
      - "./postgres/order-validation-service:/docker-entrypoint-initdb.d"
    ports:
      - "5435:5432"

  apigateway:
    container_name: apigateway
    build: ./api-gateway
    image: aswproject/apigateway:2024-01
    ports:
      - "8080:8080"
    depends_on:
      consul:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - order-manager

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: asw-project@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  order-service-db-data:
    name: order-service-db-data
  product-service-db-data:
    name: product-service-db-data
  pgadmin-data: